### ISSUE TITLE
MIDI <-> TCP/IP Socket Bridge

### ISSUE THREAD

**Issue by DRSDavidSoft** [projectgus/hairless-midiserial#26]
Hi again,

I'm working on a project that uses Ethernet to communicate with the PC running Hairless MIDI Bridge. I'm currently using a TCP/IP to Virtual Serial Port Bridge to redirect the data from Ethernet to Hairless MIDI Bridge, but I thought it'd be better if your awesome app could support TCP/IP "natively".

Perhaps you could add the options in the 'Preferences' menu to select the IP and the port.

Thanks!

**Comment by projectgus** [comment]
Hi,

Thanks, that's an interesting suggestion. I've thought about supporting some kind of MIDI network protocol in Hairless before, as a Serial<->Network MIDI link, but in the end I decided that once you have the serial data available to the local OS as MIDI, you can use existing MIDI network drivers to connect it to the network using whatever protocol you need.

If all you need is a network<->MIDI link, there are other tools that do this well already. You may want to look at existing MIDI-over-IP protocols. Some examples are RTP-MIDI and OSC (which isn't MIDI, but solves the same problem.)

BTW, FWIW TCP is not a good transport choice for real-time data such as MIDI because it can introduce unexpected latency problems.

Cheers,


Angus
