### ISSUE TITLE
installation on ubuntu

### ISSUE THREAD

**Issue by danielneumaier2222** [projectgus/hairless-midiserial#47]
Hi!
i tried to install this tool on Ubuntu. But i can't run the application/x-executable filetype. Dr. Google couldn't help me. The error message is: "./hairless-midiserial: Kann die Datei nicht ausführen."
In english: "./hairless-midiserial: file not executable". Do i need any lib to run this file or is there any bash-file available?

Thanks for any help

**Comment by sleeplessCortes** [comment]
I am having the same problem.  the "funny" thing about it------ I had it allready running, but then I installed "Bristol" with some jackstuff and after that it didnt work anymore (different errormessage, something with "cannot open alsa.pulse.plugin"), so I made up a new Ubuntu system on different partition in hope it would work there again, but now I have the same error........:(

**Comment by jayknowstheway** [comment]
Still not working, same error message.. i think they should not advertise it as linux compatible?

**Comment by projectgus** [comment]
If you have 64-bit Linux (most people these days have 64-bit Linux, back in 2012 when the latest Hairless release was many people still had 32-bit) then you need 32-bit compatibility libraries, or you get an error like "No such file or directory"

( This is mentioned on the Hairless home page, but there's no other info as the steps to get 32-bit support vary depending on which Linux distro you use.)

I spun up an Ubuntu 16.04 VM and these commands did the trick for me:

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libasound2:i386 libsm6:i386 libxrender1:i386 libfontconfig:i386 libxext6:i386 libstdc++6:i386 libasound2-plugins:i386
```

> i think they should not advertise it as linux compatible?

If I ever invent time travel I'll make sure to go back to 2012 and let myself know..

**Comment by jayknowstheway** [comment]
Hi Angus,

Thank you so much, i think you clarified the misunderstanding, i need to
install 32 bit support in order to get this to work. With that lead, i
think i can figure out how to get things going. I guess it just wasn't
obvious to me that this was the solution. If you add one line in the docs
saying something like, "to fix the error, you must download 32 bit
compatibility libraries, which depend on the distro you use," then there
might not be confusion around that? Anyway, i appreciate your help and
product. I had to switch to mac to get it going but it does work and got me
where i needed to go.
